//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aztec_Project.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AztecDatabaseEntities : DbContext
    {
        public AztecDatabaseEntities()
            : base("name=AztecDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<Cinema> Cinemas { get; set; }
        public virtual DbSet<ComingSoonMovie> ComingSoonMovies { get; set; }
        public virtual DbSet<ShowingMovie> ShowingMovies { get; set; }
        public virtual DbSet<Seat> Seats { get; set; }
        public virtual DbSet<TicketBooking> TicketBookings { get; set; }
        public virtual DbSet<User_Profile> User_Profile { get; set; }
    }
}
