//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aztec_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cinema
    {
        public int CinemaID { get; set; }
        public string CinemaName { get; set; }
        public string ContactNumber { get; set; }
        public string Address { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
    }
}
