//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aztec_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketBooking
    {
        public int ID { get; set; }
        public string MovieName { get; set; }
        public string Date { get; set; }
        public string SeatNo { get; set; }
        public string SeatStatus { get; set; }
        public string CustomerName { get; set; }
        public string PhoneNumber { get; set; }
    }
}
