//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aztec_Project.Models
{
    using System;
    using System.Collections.Generic;
    //using System.ComponentModel.DataAnnotations;
    
    public partial class User_Profile
    {
        public int UserID { get; set; }

        //[Required(ErrorMessage = "Please enter username", AllowEmptyStrings = false)]
        public string UserName { get; set; }

        //[Required(ErrorMessage = "Please enter password", AllowEmptyStrings = false)]
        //[DataType(System.ComponentModel.DataAnnotations.DataType.Password)]
        //[StringLength(50, MinimumLength = 8, ErrorMessage = "Password must be at least 8 characters.")]
        public string Password { get; set; }

        //[Compare("Password", ErrorMessage = "Your password does not match.")]
        //[DataType(System.ComponentModel.DataAnnotations.DataType.Password)]
        public string ConfirmPassword { get; set; }

        //[Required(ErrorMessage = "Please enter your full name", AllowEmptyStrings = false)]
        public string FullName { get; set; }
        public string EmailAddress { get; set; }
    }
}
